title: EKSPRESI
baseURL: /

paginate: 6
paginatePath: /

permalinks:
  art: /:filename/
  event: /:title/

taxonomies:
  tag: tag

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  menu1: art
  menu2: event
  menu3: profile
  cdn: 
  cover: 
  search: Search?
  facebook: https://fb.com/ekspresi
  twitter: https://twitter.com/ekspresi
  instagram: https://instagram.com/ekspresi
  copyright: • EKSPRESI (C) All Rights Reserved •
  copyrightlink: https://s.id/copyrighted
  description: Ekspresi Dalam Diri. Aktualisasi Lewat Seni.

disableHugoGeneratorInject: true
